### ISSUE TITLE
Cannot update README.md using workflows

### ISSUE THREAD

**Issue by coronarita** [coronarita1991/AIFFEL_RESEARCH_STUDY#2]
As I want to update the project tree in README.md every time I commit, I tried to use Github Actions.

However, I cannot achieve the goal what I want to. 

> I guess that the accurate setting of PAT is the key. 

![image](https://github.com/coronarita1991/AIFFEL_RESEARCH_STUDY/assets/101229388/13994b70-d304-4d36-aedc-6581d86ae7c6)

**Comment by coronarita1991** [comment]
It looks like you need to set workflow permissions.

Go Repository Settings - Actions - General - Workflow permissions.
Then, Check `Read and write permissions`
<img width="604" alt="스크린샷 2024-05-26 오전 12 15 39" src="https://github.com/coronarita1991/AIFFEL_RESEARCH_STUDY/assets/169136233/2521086b-8935-4ea4-a4c4-689676436d48">
